### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by childledj** [youridijk/homebridge-kaku-ics2000#1]
Great plugin! I've wait for it for a long time!
1. Every device connected to ICS-2000 detects like lamps, even Sockets, Switches and Sensors, will it be possible to change them? In my setup I have sockets, hidden relays, doorbell, ambient light sensor.
2. When I configure plugin via Plugins/KAKU ICS-2000/Settings - there are some collisions with config.json (e.g. Platform: "ExampleHomebrigdePlugin" instead of "KAKU-ICS2000") and vice versa when I change settings in config.json, in plugin settings everything disappears (kaku user, password etc.). 
I have stopped now on working option when I use config.json to configure KAKU plugin but in most cases it is difficult to catch that moment when everything works fine.

**Comment by arnoldwillems84** [comment]
I am experiencing teh same issue as you discribed at point 2

**Comment by childledj** [comment]
Still waiting for the plugin update

**Comment by youridijk** [comment]
I just released an update to fix the second issue. As for the first one: In only have wall sockets connected with lights and lightbulbs from KAKU, so that's why everything is a lamp in homebridge. I will change everything that you can only turn on an off to a switch in a future update, so you can decide yourself what type it is (you can say to HomeKit that a switch is a light)

**Comment by childledj** [comment]
> I just released an update to fix the second issue. As for the first one: In only have wall sockets connected with lights and lightbulbs from KAKU, so that's why everything is a lamp in homebridge. I will change everything that you can only turn on an off to a switch in a future update, so you can decide yourself what type it is (you can say to HomeKit that a switch is a light)

Thank you for your plugin and it’s support!  
I think in most cases it will be enough to choose from light, socket, switch and fan (just on and off).

**Comment by youridijk** [comment]
I just made a commit that adds your request + another feature. I'm testing this for a few days on my own homebridge setup and if it's working, I'll publish it on npm.

**Comment by arnoldwillems84** [comment]
Hi @youridijk could you please also add smoke detectors ?

**Comment by youridijk** [comment]
Since I don't own a smoke detector that works with KAKU, it will be very hard to add that functionality. I don't know how much programming skills you have, but maybe you can try it yourself! I ever own a smoke detector that works with KAKU, I'll try to add it!

**Comment by arnoldwillems84** [comment]
@youridijk ,

No worries, maybe we can help each other out with this. I am a developer but normally script in different languages and have never used TypeScript. Mainly I script in SuiteScript which is build on JavaScript.

I noticed when I update the package.json file on my server, that I can point the plugin to my forked github repo which enables me to test any changes.

I will wait till you push your final changes and will familiarize my self then with your scripts.

Is there any documentation you would recommend our that you use for this development related to the KAKU api's ?

Thanks in advance

Arnold

**Comment by youridijk** [comment]
Well if you need any help, feel free to ask! For developing this plugin I used the official documentation of homebridge and [this](https://github.com/Stijn-Jacobs/ICS2000-Python) library written in Python. I rewrote parts of the library in TypeScript to use with this plugin. There isn't really documentation available, but the code of Stijn really explains itself and I will write some documentation for the KAKU api. 
The API in brief: The Hub (ICS-2000) works with encrypted UPD messages (128-AES, IV is all zero's and encryption keys is stored on your account on Trust server). This messages are directly send to the Hub from your device.  In this message you specify the new status of a specified device. The (encrypted with same key as mentioned before) list of devices is stored on Trust server along with current status of the devices (the server knows status for all devices, also the devices that officially don't support it, like wall plugs not using Zigbee). For more details, take a look at Stijn's library or my code in the KAKU folder (the files in that folder are used for communication with the Hub).

**Comment by jocstone** [comment]
Hi all, I know nothing about scripting but happy to test or provide information about these things.
My homebridge runs on my qnap server.
I have all kinds of receivers and transmitters as well as some zigbee (Ledvance) wall plugs.
Also water detector.
So, please shout if anything needed 😀 
PS: also Dutch speaking.

**Comment by arnoldwillems84** [comment]
Hi all,

Thanks for the feedback and yes you guessed write I am Dutch :)
I am also running this on my QNAP and will have a look to see if I can help as its a new area for me but always good to challenge your self with new things.

Gr

**Comment by youridijk** [comment]
@jocstone Thanks for offering help! At the moment, I started writing documentation about the ICS-2000. If you want to help, you can read the docs and provide feedback, and if you want, you can improve the docs (you can help with non technical things, like better sentence structure). And if the docs are done, maybe you can translate the docs to Dutch. Because I think most people using Klik Aan Klik Uit are Dutch, it would be nice to also have Dutch. But my primary focus is making docs in English, so everyone can read it.

**Comment by childledj** [comment]
After update to 1.0.3 every kaku device began to consist of two switches - “lightbulb “ and “switch”, with only “switch” works to control device.
![646C9033-E202-43BF-9440-57E18171B127](https://user-images.githubusercontent.com/38331621/184085878-88ba8579-7c04-47c1-b287-3fdbaa82c3c5.png)

**Comment by youridijk** [comment]
@childledj Please open up a new issue for this

**Comment by youridijk** [comment]
@arnoldwillems84 I created detailed docs in the docs folder about everything I know about the ICS-2000. I hope this will help you with your development!

**Comment by youridijk** [comment]
Closing issue as the original issue is resolved
