### ISSUE TITLE
Bridge not working

### ISSUE THREAD

**Issue by Bertmobiel** [youridijk/homebridge-kaku-ics2000#10]
Hi Youri,
I'am trying to activate KaKu Ics2000 Bridge, but it is giving a yellow exclamation mark. The error in the log says 'unhandled rejection: Error: Email and/ or password missing', but that data is correct.
I hade made a ticket at Hoobs (6346-FAE2-A875-527C-62E4-3DB4). They suggested to do an update, which I did without results.
Do you have a solution for me?

Regards
Bert

**Comment by youridijk** [comment]
I never heard of Hoobs, so don't have any experience with that platform. That error isn't thrown by this library. If you don't provide a username and/ or password, the plugin throws an error saying`'Error: Missing mandatory data`. If the credentials are incorrect, the library throws an error `Error: Username/ password combination incorrect` . Maybe you could provide a screenshot of the error? Or maybe you used the wrong keys to specify the email and/or password? Could you provide a screenshot of the config for this plugin (replace your credentials with random text)?

**Comment by Bertmobiel** [comment]
Hi Yourdi,

 

Just for your information. In the past I had an account on their website (klikaanklikuit.nl), but that’s not the case anymore. The credentials are only necessary for their app (Smart Home from Trust) which is using, so it looks like,  a cloud for storing a backup. There is no data which kind of cloud this is.

 

Regards

Bert

 

 

 

Van: Bert van Wees ***@***.***> 
Verzonden: woensdag 12 oktober 2022 21:11
Aan: 'youridijk/homebridge-kaku-ics2000' ***@***.***>
Onderwerp: RE: [youridijk/homebridge-kaku-ics2000] Bridge not working (Issue #10)

 

Hi,

 

Ok, this plugin is available in the setup for a so called Hoobs box. But ok, enclosed some screenshots.

 

Regards

Bert

 

Van: Youri Dijk ***@***.*** ***@***.***> > 
Verzonden: woensdag 12 oktober 2022 20:52
Aan: youridijk/homebridge-kaku-ics2000 ***@***.*** ***@***.***> >
CC: Bertmobiel ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Onderwerp: Re: [youridijk/homebridge-kaku-ics2000] Bridge not working (Issue #10)

 

I never heard of Hoobs, so don't have any experience with that platform. That error isn't thrown by this library. If you don't provide a username and/ or password, the plugin throws an error saying'Error: Missing mandatory data. If the credentials are incorrect, the library throws an error Error: Username/ password combination incorrect . Maybe you could provide a screenshot of the error? Or maybe you used the wrong keys to specify the email and/or password? Could you provide a screenshot of the config for this plugin (replace your credentials with random text)?

**Comment by youridijk** [comment]
Please only type the text of your new comment, not the whole conversation and mail data in every comment. I can’t see ant screenshot, I guess something went wrong?

**Comment by Bertmobiel** [comment]
> Hi Youri, I'am trying to activate KaKu Ics2000 Bridge, but it is giving a yellow exclamation mark. The error in the log says 'unhandled rejection: Error: Email and/ or password missing', but that data is correct. I hade made a ticket at Hoobs (6346-FAE2-A875-527C-62E4-3DB4). They suggested to do an update, which I did without results. Do you have a solution for me?
> 
> Regards Bert

**Comment by Bertmobiel** [comment]
Hi Yourdi,

Just for your information. In the past I had an account on their website (klikaanklikuit.nl), but that’s not the case anymore. The credentials are only necessary for their app (Smart Home from Trust) which is using, so it looks like,  a cloud for storing a backup. There is no data which kind of cloud this is.

Regards
Bert
![Config1](https://user-images.githubusercontent.com/115659484/195553412-d9d66105-0681-4133-9cd4-b8627fafea91.jpg)
![Config2](https://user-images.githubusercontent.com/115659484/195553479-f44f7c53-28b2-4902-8057-b5d1c9e35c82.jpg)
![Config3](https://user-images.githubusercontent.com/115659484/195553503-c560373a-5820-448a-ab42-62089cfad30d.jpg)

**Comment by youridijk** [comment]
Try to change the platform value to `KAKU-ICS2000`. Maybe that fixes your problems.

**Comment by Bertmobiel** [comment]
I tried, but it is automaticely going back to 'ExampleHomebridgePlugin' after Save.

**Comment by youridijk** [comment]
I think you’re using an older version of this plugin. Try to delete and reinstall this plugin or update it.

**Comment by Bertmobiel** [comment]
I have done a reinstall, now it says 1.0.6, but still the wrong platform data. Can't change it.

**Comment by youridijk** [comment]
That's weird behavior. Maybe it's caching the name somewhere and that is causing the revert. 1.0.6 is the latest at the moment of writing. You were talking about errors saying missing username/password, can you provide a screenshot of that?

**Comment by Bertmobiel** [comment]
![Hoobs log](https://user-images.githubusercontent.com/115659484/195698623-3c2ede1c-9eb6-4f3c-986e-f5ab1c1d7c68.jpg)

**Comment by youridijk** [comment]
It appears to be some configuration issue. Don’t know if your provided config is correct or wrong, but this weekend I will install hoobs locally to test it out.

**Comment by Bertmobiel** [comment]
Ok, great, thanks. Will be waiting on the results.

**Comment by youridijk** [comment]
I installed HOOBS on a Debian VM and got it working. I had the same error but managed to fix it. Your need to manually edit the config of your bridge and fill in the right data. Like this:
<img width="707" alt="Config" src="https://user-images.githubusercontent.com/28221432/196268185-a897c905-7f84-4240-829d-0ed19c3d6976.png">

I don't know why HOOBS is acting so annoying with this plug-in but this works. Note: after you manually edited the config and made it working, the plug-in settings will have default values and not you're username and password.

**Comment by youridijk** [comment]
It seems that the config shown in HOOBS uses [an old version of config.schema.json](https://github.com/youridijk/homebridge-kaku-ics2000/blob/1b8a8263fc6aa665ed0debc8d23e8e313d82507d/config.schema.json), but the latest version is downloaded from NPM. Don't know why unfortunately.

**Comment by Bertmobiel** [comment]
Ok, but can I do something about it or should I report that to Hoobs?

**Comment by youridijk** [comment]
> I installed HOOBS on a Debian VM and got it working. I had the same error but managed to fix it. Your need to manually edit the config of your bridge and fill in the right data. Like this: 

I added a solution to make it working here.

**Comment by Bertmobiel** [comment]
Ok, thanks. Was able to get it working.
