### ISSUE TITLE
Add device type 36, 41 & 42 to list

### ISSUE THREAD

**Issue by jocstone** [youridijk/homebridge-kaku-ics2000#11]
Hi, I had a look at my devices and found some more device types.
The zigbee plugs cannot be turned on or off, however, the are visible as switches.

deviceType=36, is a zigbee (ledvance) dimmable and cool to warm white adjustable spot. (works now, only on and off)
deviceType=41, is a zigbee (ledvance) smart plug (on or off).
deviceType=33, is in fact the same as 41, same brand, does the same, so also zigbee smart plug (on or off)
deviceType=42, is a Kaku waterdetector, not sure if this should be visible in homebridge, just providing the deviceType.

Thanks!!

**Comment by jocstone** [comment]
It seems that deviceType=36, the zigbee spot is dimmable via the Home app, don't know if the temperature of the white light is manageable?

deviceType=42 appears as "Reload Switch"…

**Comment by youridijk** [comment]
Thanks for the information! Which deviceType has the device that's not working? Further, it's default behavior to show all devices, sensors as well. If you don't want to show sensors in your Home app, add the entityIds of the sensors to the deviceBlacklist array in your config. 

Color temp: The ICS-2000 python lib has color temp implemented. I will use his code to maken color temp available in HomeBridge, but because I don't have lights with color temp, I can't test it.

**Comment by jocstone** [comment]
For the sensor, will do that.

For the color temp, I can test this once you have something.

The devices note working are 41 and 33, both are the same brand/type devices, don't know why they have different devicetype numbers.

**Comment by youridijk** [comment]
I guess the devices are a different generation/ revision. That’s why they have different types. By the way, what do you mean with 'the devices note working'?

**Comment by jocstone** [comment]
I'm sorry, that was a typo, I meant the devices not working are 41 and 33.

**Comment by childledj** [comment]
I have found some types too:
deviceType=13 Kaku doorbell
deviceType=6 doorbell button
deviceType=4 PIR sensor
deviceType=14 ambient light sensor

**Comment by youridijk** [comment]
@childledj could you open a general issue so people can add their device types in the comments of that issue? Thanks for your help!

**Comment by jocstone** [comment]
I’ll place mine in #12 too, so this issue can be closed?

**Comment by youridijk** [comment]
You said that device types 41 en 33 are not working. Is it still not working? And yesterday I made an update to add colour temp lights. Maybe you could test it and check if it’s working before closing the issue?

**Comment by jocstone** [comment]
ow okay, I didn't noticed this, now at work, I will test this first as soon as I'm back home and keep you informed.

**Comment by jocstone** [comment]
update:
deviceType=36: I can choose warmth now for the spot, however, dimming option is gone, only on or off now.
deviceType=41 & 33: still not possible to turn on or off.
I emptied cash and restarted server.

**Comment by youridijk** [comment]
Thanks you for the feedback. I will test if a lightbulb supports brightness and color temp. If you are familiar with programming or networking, maybe you can figure out which data the Kaku api uses for 41 and 33. For more info, see the docs and [this issue](https://github.com/youridijk/homebridge-kaku-ics2000/issues/8#issuecomment-1278059693)

**Comment by Stijn-Jacobs** [comment]
> Thanks you for the feedback. I will test if a lightbulb supports brightness and color temp. If you are familiar with programming or networking, maybe you can figure out which data the Kaku api uses for 41 and 33. For more info, see the docs and [this issue](https://github.com/youridijk/homebridge-kaku-ics2000/issues/8#issuecomment-1278059693)

I don't know if you already found it but Zigbee version's indeed use different data fields from the status array. 
- 41, Uses 3 as index for on and off in the status array. (Defined as ZIGBEE_SOCKET in app code)
- 33, Uses the same 3 index for switching on and off. (ZIGBEE_SWITCH)
- 36, Uses index 9 for changing of the color temperature, and index 4 for dimming (value between 0 and 255). (ZIGBEE_TUNABLE)

**Comment by youridijk** [comment]
@Stijn-Jacobs  sorry for late response, totally forgot this issue. Thanks for the help, I already figured it out based on ICS-2000 lib for python. Maybe team up one day and add more functional to the python lib as well?
