### ISSUE TITLE
Error in log while trying to activate plugin

### ISSUE THREAD

**Issue by Quaros** [youridijk/homebridge-kaku-ics2000#17]
I have installed the plugin into HOOBS and went through the initial setup and got this error in the log:

15-12-2022 21:58:09 Kaku Ics2000 Bridge starting
15-12-2022 21:58:11 Kaku Ics2000 BridgeLoaded plugin 'homebridge-kaku-ics2000'
15-12-2022 21:58:11 Kaku Ics2000 BridgeLoading 2 platforms...
15-12-2022 21:58:11 Kaku Ics2000 BridgeWarningunhandled rejection: Error: Email and/ or password missing

I filled in my email and password in the initial configuration:

"platform": "ExampleHomebridgePlugin",
"name": "ICS-2000",
"email": "account@gmail.com",
"password": "Password123#456",
"localBackupAddress": "xxx.xxx.xxx.xxx"

Changed the password a few times, because maybe it doesn't like characters like # or ! in the password. Checked it with the KAKU app on my phone,  But still got the above error mentioning the email and password missing.

Am I doing something wrong?

**Comment by youridijk** [comment]
This is a weird issue with HOOBS. Take a look at issue #10 . Same issue over their, I that that fixed it.

**Comment by Quaros** [comment]
Thank you very much for your quick reply. I got it working with your tips in issue #10.
