### ISSUE TITLE
Plugin is slowing down homebridge

### ISSUE THREAD

**Issue by DeManMetDeHamer** [youridijk/homebridge-kaku-ics2000#2]
Homebridge keeps giving the error in the logs below.
[homebridge.log.txt](https://github.com/youridijk/homebridge-kaku-ics2000/files/9052072/homebridge.log.txt)

I see my kaku devices but cannot control them.
Any ideas what i can do to fix this?

**Comment by youridijk** [comment]
It appears that fetching the list of devices saved on you account is successful, but fetching the status of you devices fails. Maybe something blocks these requests (the status of your devices is being fetched from https://trustsmartcloud2.com/ics2000_api/entity.php so make sure that url is reachable from homebridge)?

**Comment by DeManMetDeHamer** [comment]
> It appears that fetching the list of devices saved on you account is successful, but fetching the status of you devices fails. Maybe something blocks these requests (the status of your devices is being fetched from https://trustsmartcloud2.com/ics2000_api/entity.php so make sure that url is reachable from homebridge)?

Hi Youri,

There actually is nothing setup that could be blocking the url. Also a wget to the root url seems to work:

Length: 647 [text/html]
Saving to: 'trustsmartcloud2.com/index.html'

trustsmartcloud2.com/index.html     0%[                                                           ]       0  --.-KB/trustsmartcloud2.com/index.html   100%[==========================================================>]     647  --.-KB/s    in 0s      

2022-08-16 23:34:22 (24.3 MB/s) - 'trustsmartcloud2.com/index.html' saved [647/647]

Accessing the api shows a 400 but i think this is because of missing data in my request?

**Comment by DeManMetDeHamer** [comment]
Seems like after an update of the plugin it is now fully functional!
