### ISSUE TITLE
Hiding reload switch

### ISSUE THREAD

**Issue by dionvl** [youridijk/homebridge-kaku-ics2000#20]
This plugin is exactly what I was looking for and it has been working flawlessly so far. Thank you so much to all the devs who've made this possible. My request is a separate option to hide the reload switch, as it runs every night anyway. 
Maybe there is no need for the reload switch at all? My local IP for the ICS is static and the AES key doesn't change as far as I know.

**Comment by youridijk** [comment]
Not everyone has a static ip for the ICS-2000. Besides pulling the aes key and ip of the hub, the switch reloads all the devices currently added to the app of kaku. So if you add a device in the app you can use the reload switch to add the device to homebridge. And whenever this plugin is not responding, the reload switch always seems to fix it is my experience. So it’s not useless but I will make an option to disable the switch.

**Comment by youridijk** [comment]
Closing as feature is completed
