### ISSUE TITLE
Plugin does not show pairing and overrides platform and stops running

### ISSUE THREAD

**Issue by arnoldwillems84** [youridijk/homebridge-kaku-ics2000#4]
Hi,

When the plugin is installed the value platform will be set to "ExampleHomebridgePlugin" and the plugin will not run.
When I override this to "KAKU-ICS2000" the plugin will run and shows a green light. Each time the Homebridge get restarted our if I click Setting for the plugin it will be reverted back.

When I go to Bridge Settings and Switch the toggle on to show to generate the QR code and follow the steps to restart it will not show a QR code and keeps showing the message "Restart Homebridge to finish setting up this child bridge.
Return to this screen after Homebridge has restarted to view the pairing QR code."

Also the logs will show me this message on startup and will only show when this plugin is activated
"No plugin was found for the platform "ExampleHomebridgePlugin" in your config.json. Please make sure the corresponding plugin is installed correctly."

Hopefully you can get this solved

Thanks

**Comment by youridijk** [comment]
The first and third point is fixed (same bug). But I don't understand your second issue? What is it that you are trying to do? Setup a child bridge? If so, that has nothing to do with this plugin.

**Comment by Rosalems** [comment]
thanks @youridijk for your quick response and implementing this fix. This solved all my issue and I am now able to use the plugin in my apple home
Have a nice weekend

Cheers

**Comment by arnoldwillems84** [comment]
thanks @youridijk for your quick response and implementing this fix. This solved all my issue and I am now able to use the plugin in my apple home
Have a nice weekend

Cheers
