### ISSUE TITLE
Dimmers are shown as switches

### ISSUE THREAD

**Issue by RonaldR** [youridijk/homebridge-kaku-ics2000#8]
Hi!
Thanks for this plugin! Some of my lights in kaku are dimmable, but in homebridge/homekit they now show up as switches. Is this a setting I missed?

Thanks!

**Comment by youridijk** [comment]
You did nothing wrong! Every device has an integer defining which device type it is (zigbee switch, dimmable, etc). The list of device types that are dimmable devices isn't complete. If you can provide the device types of your devices, I will add them to the plugin. You can find this integer behind your device name when homebridge is booting ('Loaded device from cache: [device name]: [your device type]' . In addition to that, I will add an option to the plugin settings where you can specify which devices are dimmable.

**Comment by RonaldR** [comment]
Awesome, thanks!
This is an example of a dimmable light: `[ICS-2000] Loaded device from cache: Eet tafel: 2`

**Comment by RonaldR** [comment]
Added a PR: https://github.com/youridijk/homebridge-kaku-ics2000/pull/9

**Comment by youridijk** [comment]
Thanks for your PR!

**Comment by RonaldR** [comment]
Are you going to publish the new version to npmjs?

**Comment by youridijk** [comment]
Yes I will. I always wait a few days so I can test it on my own homebridge setup. I will publish it this evening.

**Comment by youridijk** [comment]
You could try to re-add the homebridge hub to your home

**Comment by RonaldR** [comment]
I tried the re-add, but they are still switches.

**Comment by RonaldR** [comment]
I'm getting this debug info:
`This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

**Comment by RonaldR** [comment]
Since 1.0.6 the lights now show as dimmers (and switches), but they are not working. Getting this log:
`[homebridge-kaku-ics2000] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.`

**Comment by youridijk** [comment]
My guess is that the different device types use different data from the status array. The current behavior of dimmable devices is based on the devices I can test with. Maybe you could figure out which data your devices use for the dim level? I documented the research of others (especially from the python variant of this plugin) and my own. For now, you need to manually interact with the KAKU api, but I am working on a REST server so anyone can easily communicate with the KAKU api.

**Comment by RonaldR** [comment]
I added a PR to add device type 2 functionality: https://github.com/youridijk/homebridge-kaku-ics2000/pull/13

**Comment by youridijk** [comment]
Thanks for the PR! For now it's fine, but I will make a good way to define the functions integers for on/off, brightness, etc for every device type.
